version: '3'

services:
  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ./app/.env.local
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '4306:3306'
    volumes:
      - ./etc/docker/mysql:/var/lib/mysql
  php:
    container_name: php
    build:
      context: etc/docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/bildia
    depends_on:
      - database
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/bildia
      - ./etc/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database